-- MySQL Script generated by MySQL Workbench
-- Thu Feb 27 10:37:37 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema delivopt
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `delivopt` ;

-- -----------------------------------------------------
-- Schema delivopt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `delivopt` DEFAULT CHARACTER SET utf8 ;
USE `delivopt` ;

-- -----------------------------------------------------
-- Table `delivopt`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivopt`.`Address` ;

CREATE TABLE IF NOT EXISTS `delivopt`.`Address` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(255) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `postcode` VARCHAR(20) NOT NULL,
  `latitude` DECIMAL(9,6) NOT NULL,
  `longitude` DECIMAL(9,6) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `delivopt`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivopt`.`Client` ;

CREATE TABLE IF NOT EXISTS `delivopt`.`Client` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `client_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `phone_number` VARCHAR(20) NULL DEFAULT NULL,
  `address_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`email` ASC) VISIBLE,
  INDEX `fk_Client_Address1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `delivopt`.`Address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `delivopt`.`Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivopt`.`Company` ;

CREATE TABLE IF NOT EXISTS `delivopt`.`Company` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(45) NULL,
  `address_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Company_Address1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_Company_Address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `delivopt`.`Address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivopt`.`Warehouse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivopt`.`Warehouse` ;

CREATE TABLE IF NOT EXISTS `delivopt`.`Warehouse` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `warehouse_address_id` BIGINT NULL DEFAULT NULL,
  `warehouse_name` VARCHAR(255) NOT NULL,
  `owner_company_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`warehouse_address_id` ASC) VISIBLE,
  INDEX `fk_Warehouse_Company1_idx` (`owner_company_id` ASC) VISIBLE,
  CONSTRAINT `fk_warehouse_address`
    FOREIGN KEY (`warehouse_address_id`)
    REFERENCES `delivopt`.`Address` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_Warehouse_Company1`
    FOREIGN KEY (`owner_company_id`)
    REFERENCES `delivopt`.`Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `delivopt`.`Goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivopt`.`Goods` ;

CREATE TABLE IF NOT EXISTS `delivopt`.`Goods` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `goods_name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `weight` DECIMAL(10,2) NOT NULL,
  `volume` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `delivopt`.`Warehouse_Goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivopt`.`Warehouse_Goods` ;

CREATE TABLE IF NOT EXISTS `delivopt`.`Warehouse_Goods` (
  `warehouse_id` BIGINT NOT NULL,
  `goods_id` BIGINT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`warehouse_id`, `goods_id`),
  INDEX `fk_goods` (`goods_id` ASC) VISIBLE,
  CONSTRAINT `fk_warehouse`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `delivopt`.`Warehouse` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_goods`
    FOREIGN KEY (`goods_id`)
    REFERENCES `delivopt`.`Goods` (`id`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `delivopt`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivopt`.`Orders` ;

CREATE TABLE IF NOT EXISTS `delivopt`.`Orders` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `client_id` BIGINT NOT NULL,
  `destination_address_id` BIGINT NOT NULL,
  `order_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  `status` ENUM('PENDING', 'IN TRANSIT', 'DELIVERED') NULL DEFAULT 'PENDING',
  PRIMARY KEY (`id`),
  INDEX `fk_order_client` (`client_id` ASC) VISIBLE,
  INDEX `fk_delivery_address` (`destination_address_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `delivopt`.`Client` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_delivery_address`
    FOREIGN KEY (`destination_address_id`)
    REFERENCES `delivopt`.`Address` (`id`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `delivopt`.`Ordered_Warehouse_Goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivopt`.`Ordered_Warehouse_Goods` ;

CREATE TABLE IF NOT EXISTS `delivopt`.`Ordered_Warehouse_Goods` (
  `order_id` BIGINT NOT NULL,
  `quantity` INT NOT NULL,
  `warehouse_id` BIGINT NOT NULL,
  `goods_id` BIGINT NOT NULL,
  PRIMARY KEY (`order_id`, `warehouse_id`, `goods_id`),
  INDEX `fk_Ordered_Goods_Warehouse_Goods1_idx` (`warehouse_id` ASC, `goods_id` ASC) VISIBLE,
  CONSTRAINT `fk_ordered_goods_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `delivopt`.`Orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ordered_Goods_Warehouse_Goods1`
    FOREIGN KEY (`warehouse_id` , `goods_id`)
    REFERENCES `delivopt`.`Warehouse_Goods` (`warehouse_id` , `goods_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `delivopt`.`Car`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivopt`.`Car` ;

CREATE TABLE IF NOT EXISTS `delivopt`.`Car` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `car_type` VARCHAR(50) NOT NULL,
  `max_weight_capacity` DECIMAL(10,2) NOT NULL,
  `max_volume_capacity` DECIMAL(10,2) NOT NULL,
  `owner_company_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Car_Company1_idx` (`owner_company_id` ASC) VISIBLE,
  CONSTRAINT `fk_Car_Company1`
    FOREIGN KEY (`owner_company_id`)
    REFERENCES `delivopt`.`Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `delivopt`.`Routes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivopt`.`Routes` ;

CREATE TABLE IF NOT EXISTS `delivopt`.`Routes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `from_address_id` BIGINT NOT NULL,
  `to_address_id` BIGINT NOT NULL,
  `distance_km` DECIMAL(10,2) NOT NULL,
  `estimated_time_min` INT NOT NULL,
  `last_updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `fk_route_origin_address` (`from_address_id` ASC) VISIBLE,
  INDEX `fk_route_destination_address` (`to_address_id` ASC) VISIBLE,
  CONSTRAINT `fk_route_origin_address`
    FOREIGN KEY (`from_address_id`)
    REFERENCES `delivopt`.`Address` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_route_destination_address`
    FOREIGN KEY (`to_address_id`)
    REFERENCES `delivopt`.`Address` (`id`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `delivopt`.`Delivery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivopt`.`Delivery` ;

CREATE TABLE IF NOT EXISTS `delivopt`.`Delivery` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `car_id` BIGINT NULL,
  `departure_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  `estimated_arrival_time` DATETIME NULL DEFAULT NULL,
  `type` ENUM('WAREHOUSE_TO_CLIENT', 'WAREHOUSE_TO_WAREHOUSE') NULL,
  INDEX `fk_delivery_car` (`car_id` ASC) INVISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_delivery_car`
    FOREIGN KEY (`car_id`)
    REFERENCES `delivopt`.`Car` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `delivopt`.`Orders_Delivery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivopt`.`Orders_Delivery` ;

CREATE TABLE IF NOT EXISTS `delivopt`.`Orders_Delivery` (
  `order_id` BIGINT NOT NULL,
  `delivery_id` BIGINT NOT NULL,
  INDEX `fk_orders_delivery_Orders1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_orders_delivery_Delivery1_idx` (`delivery_id` ASC) VISIBLE,
  PRIMARY KEY (`order_id`, `delivery_id`),
  CONSTRAINT `fk_table1_Orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `delivopt`.`Orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_table1_Delivery1`
    FOREIGN KEY (`delivery_id`)
    REFERENCES `delivopt`.`Delivery` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivopt`.`Delivery_routes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivopt`.`Delivery_routes` ;

CREATE TABLE IF NOT EXISTS `delivopt`.`Delivery_routes` (
  `route_id` BIGINT NOT NULL,
  `delivery_id` BIGINT NOT NULL,
  `sequence` INT NOT NULL,
  INDEX `fk_table1_Routes1_idx` (`route_id` ASC) VISIBLE,
  PRIMARY KEY (`route_id`, `delivery_id`),
  INDEX `fk_table1_Delivery2_idx` (`delivery_id` ASC) VISIBLE,
  CONSTRAINT `fk_table1_Routes1`
    FOREIGN KEY (`route_id`)
    REFERENCES `delivopt`.`Routes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_table1_Delivery2`
    FOREIGN KEY (`delivery_id`)
    REFERENCES `delivopt`.`Delivery` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
